### PR TITLE
Added pointers, renamed pages folder to home, passed through query st…

### PR DESCRIPTION
**Pull request by benbenbuhben**
…ring to dashboard

### CODE REVIEW

**Comment by justeban** [comment]
Nice PR man!

**Comment by justeban** [comment]
I'm gonna go ahead and delete your branch.

**Comment by justeban** [comment]
It works too! That was quite a bit easier then I expected.

**Comment by benbenbuhben** [comment]
Yeah. There's still some finnicky behavior though. If you have an
assignment query it'll take you to that page on the student view. But if
you try and refresh the page, it takes you back to the unpopulated
dashboard, and if you hit the back button it doesn't take you back! I'll
take a look later.

**Comment by justeban** [comment]
Yeah we might have to hijack control of the refresh button... if that is such a thing. But that brings us to a new issue in GH.

**Comment by benbenbuhben** [comment]
And I noticed we're removing the cookies on logout on the frontend. Is
there any reason we can't set that cookie domain as .env variable also
(since we don't have any env variables there yet)? Which means we'll need
to put it as a config var on heroku too. I can do that.

**Comment by justeban** [comment]
That would be a good idea. I'm not sure why, but I was under the impression that would have to do something different in order to properly get the env variables on our front end because we have a Webpack build. But that seems to be a pretty reasonable solution. 

We'll see if it works...

**Pull request merged**
